# Generated by Django 4.0.5 on 2022-06-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_options_remove_clientes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
